
services:
  # Backend API
  petcare-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=PetCareAuth;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - petcare-network

  # Frontend React App
  petcare-frontend:
    build: 
      context: ./PetCareFrond
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - petcare-api
    networks:
      - petcare-network
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api

  # Database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: YourStrong@Passw0rd
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - "14433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - petcare-network

networks:
  petcare-network:
    driver: bridge

volumes:
  sql_data: 