services:
  petcare-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=PetCareAuth;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - ConnectionStrings__CuidadoresConnection=Server=db;Database=PetCareCuidadores;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: YourStrong@Passw0rd
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - "14433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
